version: '3.7'

services:

  # --------------- #
  # Apache Spark    #
  # --------------- #
  spark:
    image: bitnami/spark:3.3
    environment:
      - SPARK_MODE=${SPARK_MODE_MASTER}
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
      
  spark-worker:
    image: bitnami/spark:3.3
    environment:
      - SPARK_MODE=${SPARK_MODE_WORKER}
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
    volumes:
      - ./data:/data
      - ./src:/src
  

  # --------------- #
  # Apache Kafka    #
  # --------------- #
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.3
    ports:
      - '9092:9092'
      - '19092:19092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      - KAFKA_CFG_LISTENERS=INTERNAL://:19092,EXTERNAL://:9092,DOCKER://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
